Dialback SMS sending
praekeltfoundation/ndoh-jsbox pull request #49
Opened 2016-09-16 07:42 UTC by NicolaasDieBaas

Clarification is needed on how often these should be sent (current implementation is only once per identity).
Should be applied in multiple registration lines.

2016-09-16 08:52 UTC, gsvr commented on go-app-ussd_clinic.js
> +                registrant_info.details.clinic.redial_sms_sent = self.im.user.answers.redial_sms_sent;
You could just put this in the dict in the line above to make it a bit clearer, i.e.
`registrant_info.details.clinic = {redial_sms_sent: self.im.user.answers.redial_sms_send}`

2016-09-16 13:11 UTC, NicolaasDieBaas commented
@gsvr please review

2016-09-20 10:28 UTC, gsvr commented on test/ussd_public.test.js
> +            it("updates identity with redial_sms_sent 'false'", function() {
Change this description to `should not send dial-back sms when timeout occurs on a non-dialback state` or something similar.

2016-09-20 10:31 UTC, gsvr commented on test/ussd_chw.test.js
> +            it("send if redial sms not yet sent", function() {
I'd like to see explicit testing for when an identity loads with and without the `chw.redial_sms_sent` field, and similar for other apps. You don't need to complete the whole flow, just this part.

2016-09-20 19:01 UTC, NicolaasDieBaas commented
@gsvr another review please

2016-09-21 07:17 UTC, gsvr commented on test/ussd_clinic.test.js
> +            it("send if redial sms not yet sent (identity loads without redial_sms_sent set as 'false')", function() {
`without` it set as 'false'? that seems the same as the first test.

2016-09-21 07:21 UTC, gsvr commented on test/ussd_public.test.js
> +            it("send if redial sms not yet sent (identity loads without redial_sms_sent set as 'false')", function() {
same here with `without`

2016-09-21 07:24 UTC, gsvr requested changes

2016-09-21 07:31 UTC, NicolaasDieBaas commented on test/ussd_clinic.test.js
> +            it("send if redial sms not yet sent (identity loads without redial_sms_sent set as 'false')", function() {
'without' should be 'with'... i'll make the changes

2016-09-21 07:34 UTC, NicolaasDieBaas commented
@gsvr yet another review please

2016-09-21 08:06 UTC, gsvr commented on test/ussd_chw.test.js
> +                .setup.user.addr("27820001008")
This identity only has it set to `false` for `nurseconnect` - it should be `false` for all the lines you're testing it against.

2016-09-21 08:06 UTC, gsvr requested changes

2016-09-21 08:23 UTC, NicolaasDieBaas commented on test/ussd_chw.test.js
> +                .setup.user.addr("27820001008")
oops yes!! sorry.  will change

2016-09-21 08:29 UTC, NicolaasDieBaas commented
@gsvr review please

2016-09-21 09:05 UTC, gsvr approved these changes

2016-09-21 09:34 UTC, merged