NurseConnect add metrics
praekeltfoundation/ndoh-jsbox pull request #74
Opened 2016-09-29 07:17 UTC by NicolaasDieBaas

2016-09-29 07:50 UTC, NicolaasDieBaas commented
@gsvr please review.  The first block/list of commits are due to merge-in with #73

2016-10-14 06:16 UTC, NicolaasDieBaas commented
@gsvr please review

2016-10-14 12:23 UTC, gsvr requested changes
Approved after a minor change

2016-10-14 12:23 UTC, gsvr commented on test/ussd_nurse.test.js
> +                        assert.deepEqual(metrics['test.ussd_nurse.self.registration_started'].values, [1]);
just change this to `test_ussd_nurse.registrations_started` - note the plural, and that I don't want to track the `self` and `other` seperately.

2016-10-14 15:34 UTC, NicolaasDieBaas commented
resolving https://github.com/praekeltfoundation/ndoh-jsbox/issues/79 inside this issue

2016-10-14 17:26 UTC, merged